loki:
  persistence:
    enabled: true
    size: 20Gi
    storageClassName: "standard"
  tableManager:
    enabled: true
    retention_deletes_enabled: true
    retention_period: 168h 
grafana:
  enabled: true
  sidecar:
    datasources:
      label: grafana_datasource
      labelValue: "1"
      enabled: true
      maxLines: 1000
  image:
    tag: 10.3.3
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "standard"
  adminUser: admin
  adminPassword: Str0ngPassw0rd!
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      cert-manager.io/cluster-issuer: "letsencrypt-production"
    hosts:
      - host: monitoring.longppham5.xyz
        paths: 
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: grafana-tls
        hosts:
          - monitoring.longppham5.xyz
prometheus:
  enabled: true
  isDefault: true
  server: 
    persistentVolumeClaim:  
      enabled: true
      size: 20Gi
      storageClassName: "standard"